import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Hero/Header";
import Navbar from "./components/Navbar";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata: Metadata = {
  title: "TirtaMed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>TirtaMed</title>
        {/* <link rel="icon" href="@/public/logo.png" /> */}
        <link
          rel="icon"
          href="@/public/logo.png"
          type="image/png"
          sizes="32x32"
        />
        <meta name="designer" content="Yohannes Mesay" />
      </head>
      <body className={`${poppins.className}`}>
        <Header />
        <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
